[package]
name = "overlay"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dlopen = { path = "./dlopen/" }
egui = "0.18.1"
lazy_static = "1.4.0"
libc = "0.2"
glad-gl = { path = "./glad-gl/" }
